// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxR4LyfpaX52PRFd8q2ZTTUqtiPhC6Aw', 
    appId: '1:142426158895:web:85dd219a27fc834a943e77',
    messagingSenderId: '142426158895',
    projectId: 'glub-hidratado', 
    authDomain: 'Glub-Hidratado.firebaseapp.com',
    databaseURL: 'https://glub-hidratado-default-rtdb.firebaseio.com',
    storageBucket: 'glub-hidratado.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjxR4LyfpaX52PRFd8q2ZTTUqtiPhC6Aw', 
    appId: '1:142426158895:web:85dd219a27fc834a943e77', 
    messagingSenderId: '142426158895',
    projectId: 'glub-hidratado', 
    databaseURL: 'https://glub-hidratado-default-rtdb.firebaseio.com',
    storageBucket: 'glub-hidratado.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjxR4LyfpaX52PRFd8q2ZTTUqtiPhC6Aw', 
    appId: '1:142426158895:web:85dd219a27fc834a943e77', 
    messagingSenderId: '142426158895',
    projectId: 'glub-hidratado', 
    databaseURL: 'https://glub-hidratado-default-rtdb.firebaseio.com',
    storageBucket: 'glub-hidratado.appspot.com', 
    iosClientId: '142426158895-g1hg2btrs68n9aq1rl4a5rpb327ishcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.glub_hidratado',
  );
}
